name: Build & Deploy

#The Trigger
on:
  push:
    branches:
      - master
    paths:
      - 'app/**'

jobs:
  build-and-deploy:
    #The runner
    runs-on: ubuntu-latest
    
    steps:
    #Pre-built actions
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      #Advanced docker layer caching

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kube-snake-game:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

# THE UPGRADED PRODUCTION STEP: No SSH, No Sudo!
    - name: Authenticate and Trigger Kubernetes Rollout
      uses: steebchen/kubectl@v3
      with:
        config: '' # Leaving this blank forces the action to authenticate natively via variables below
      env:
        KUBE_URL: ${{ secrets.EC2_PUBLIC_IP }} # Your https://:6443 address
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}   # Your granular RBAC token
        # In sandbox setups with self-signed cluster certs, skip verification check:
        KUBE_INSECURE_SKIP_TLS_VERIFY: true 
      run: |
        kubectl set image deployment/snake-game-deployment \
          snake-game=${{ secrets.DOCKERHUB_USERNAME }}/kube-snake-game:${{ github.sha }} --namespace=default
        
        kubectl rollout status deployment/snake-game-deployment --namespace=default
          
        